name = 'portfolio'
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "portfolio_db"
database_name = "portfolio-db"
database_id = "5ebb0eb2-9b3f-4674-909b-e025252fc95f"
migrations_dir = "drizzle/migrations"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "portfolio-assets"
